name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        repository: numpy/numpy
        ref: v1.26.5
        submodules: true
        # fetch-depth: 0

    - uses: actions/setup-python@main
      with:
        python-version: 3.13

    - run: |
        choco install -y pkgconfiglite
        pip install -r requirements/build_requirements.txt
        pip wheel . -Ccompile-args="-j2" -Csetup-args="-Dallow-noblas=true

    - uses: actions/upload-artifact@main
      with:
        path: dist
        name: numpy
