name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: numpy/numpy
        fetch-depth: 0

    - uses: actions/setup-python@v3
      with:
        python-version: 3.11.0-alpha - 3.11.x

    - run: pip install -U setuptools wheel Cython # pip install -r test_requirements.txt
    
    - run: |
        mkdir openblas
        cp $(python tools/openblas_support.py) openblas/openblas.a
        python -c "from tools import openblas_support; openblas_support.make_init('numpy')"

    - run: pip wheel -v --no-build-isolation --no-use-pep517 --wheel-dir=dist .

    - uses: actions/upload-artifact@v3
      with:
        path: dist
        name: numpy-nightly
