name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        repository: numpy/numpy
        ref: v1.26.5

    - uses: actions/setup-python@main
      with:
        python-version: 3.13

    # - run: pip install -U setuptools<60 wheel Cython # pip install -r test_requirements.txt
    # - run: pip install https://github.com/cython/cython/archive/refs/heads/master.zip

    - run: |
        #mkdir openblas
        #cp $(python tools/openblas_support.py) openblas/openblas.a
        #python -c "from tools import openblas_support; openblas_support.make_init('numpy')"

    # - run: pip wheel -v --no-build-isolation --no-use-pep517 --wheel-dir=dist .
    - run: pip wheel -v --wheel-dir=dist .

    - uses: actions/upload-artifact@main
      with:
        path: dist
        name: numpy
